name: chatapps
services:
  mysql:
    image: mysql:latest
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - chatapps
    volumes:
      - ./data/mysql/data:/var/lib/mysql/data
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces"
        ]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/cassandra/data:/var/lib/cassandra/data
    networks:
      - chatapps

  chat-server:
    build: ./chat-server
    env_file:
      - ./.env
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "${CHAT_SERVER_PORT:8080}:8080"
    networks:
      - chatapps

  chat-api:
    build: ./chat-api
    env_file:
      - ./.env
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${CHAT_API_PORT:8081}:8081"
    networks:
      - chatapps

  chat-ui:
    build: ./ui
    ports:
      - "${CHAT_UI_PORT:3000}:80"
    env_file:
      - ./.env
networks:
  chatapps:
