name: chatapps
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: chatapps
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - chatapps
    volumes:
      - ./data/mysql/data:/var/lib/mysql/data
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces"
        ]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/cassandra/data:/var/lib/cassandra/data
    networks:
      - chatapps

  chat-server:
    build: ./chat-server
    image: vinh412/chat-server
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - PORT=8080
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - chatapps

  chat-api:
    build: ./chat-api
    image: vinh412/chat-api
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - PORT=8081
      - CHAT_SERVER_HOSTNAME=chat-server
      - CHAT_SERVER_PORT=8080
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - chatapps

  chat-ui:
    build: ./ui
    image: vinh412/chat-ui
    environment:
      - REACT_APP_API_SERVER_URL=http://chat.vinhdd.io.vn:8081
      - REACT_APP_CHAT_SERVER_URL=http://chat.vinhdd.io.vn:8080
    ports:
      - "80:80"
networks:
  chatapps:
