server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatapps
    username: root
    password: 123
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
